{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "springboot-argocd.serviceAccountName" . }}
  labels:
    {{- include "springboot-argocd.labels" . | nindent 4 }}
{{- end }}
