#2. Create k8s ConfigMap with argocd-vault-plugin configuration that will be mounted in the sidecar container, and overwrite default processing of Helm Charts on ArgoCD.
kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
type: Opaque
stringData:
  AVP_AUTH_TYPE: "k8s"
  AVP_K8S_ROLE: "argocd"
  AVP_TYPE: "vault"
  VAULT_ADDR: "http://vault.toolbox:8200"