apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-argocd-demo
spec:
  destination:
    namespace: toolbox
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/helm
    repoURL: https://github.com/prabakaran88/springboot-argocd
    targetRevision: main
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            serviceAccount:
              create: true
            image:
              repository: innotigers/springboot-argocd
              tag: latest
              pullPolicy: IfNotPresent
            replicaCount: 1
            resources:
              memoryRequest: 256Mi
              memoryLimit: 512Mi
              cpuRequest: 500m
              cpuLimit: 1 
            probes:
              liveness:
                initialDelaySeconds: 15
                path: /actuator/health/liveness
                failureThreshold: 3
                successThreshold: 1
                timeoutSeconds: 3
                periodSeconds: 5
              readiness:
                initialDelaySeconds: 15
                path: /actuator/health/readiness
                failureThreshold: 3
                successThreshold: 1
                timeoutSeconds: 3
                periodSeconds: 5
            ports:
              http:
                name: http
                value: 8080
              management:
                name: management
                value: 8081
            envs:
              - name: greeting.message
                value: <path:kv-v2/data/demo#message>
              - name: DB_HOST
                value: <path:kv-v2/data/rds_service#host>
              - name: DB_NAME
                value: <path:kv-v2/data/rds_service#name>
              - name: DB_USERNAME
                value: <path:kv-v2/data/rds_service#username>
              - name: DB_PASSWORD
                value: <path:kv-v2/data/rds_service#password>            
            log:
              level:
                spring: "info"
                service: "info"
  syncPolicy: {}
